language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TEST=ci
  - TEST=ruling
matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "WTjFHr7/mly14hxjweSnrWeRc8ZcwA9Fe1ed18266Q1w1FMKTJ4MrSuPw0fCczEzVHIwyfAWexZs9EhQFdwFZNOEAgqUsfqe+8rgapmDj2UbCWI9lkBqGUJnIoY24J+6HiZrqBmETlEr1SEpL/UloPNes2uagnX515WCJVkVucw="
